[package]
name = "paths"
version = "0.1.0"
edition = "2021"
description = "Paths."
license = "unlicensed"
repository = "https://github.com/rainsound-ai/rainsound.ai/"

[dependencies]
camino = "1.1.9"
